### ISSUE TITLE
Enable sphinx recognition in our app

### ISSUE THREAD

**Issue by psibre** [EllaVator/EllaVator#24]
We currently run the [OpenDialDemo](../blob/006269af5397c32856432c9c2ae28c34841ca496/src/main/java/OpenDialDemo.java) from gradle (with the `run` task), but there is no integration with sphinx, so no ASR support.
We need to add ASR support, similar to the [OpenDial Sphinx ASR plugin](https://github.com/plison/opendial/releases/download/version1.3b/sphinx-plugin.zip), and run it with our dictionary and grammar.

**Comment by StalVars** [comment]
I am looking into it ..

**Comment by naszka** [comment]
I don't understand how OpenDial and sphinx communicate. How do updatedVars get updated ( I am talking about the trigger method)? Looks like opendial handles the user speech input:
(new Thread(new RecognitionProcess((SpeechData) speechVal))).start();
opendial passes on the raw speech input?

**Comment by psibre** [comment]
The way I understand it, opendial does this by means of its Sphinx ASR plugin. We can do it similarly, but in our own codebase. Perhaps all we have to do is emulate the plugin (recall that we already have all of its dependencies in our `sphinx4` subproject).

**Comment by naszka** [comment]
Yes, I agree. I am only fuzzy about one line
line 166            state.hasChanceNode(speechVar)
Does this refer to opendial domain file? We should define for each state that it can receive speech input? Or what does this mean?

**Comment by StalVars** [comment]
Can we just add the file SphinxASR.java to the plugins ./src/opendial/plugins  and build on it?We can  use this plugin SphinxASR.java ,right?

**Comment by psibre** [comment]
I think we also need to endow opendial with the capability to load the plugin. Quoting from the `README.txt`:
> The easiest way is to add the following to your domain specification:
```xml
	<settings>
		<modules>opendial.plugins.SphinxASR</modules>
		<grammar>add here the path to your grammar file</grammar>
	</settings>
```

**Comment by naszka** [comment]
We integrated (to some extent) sphinx using this plugin. I pushed it to my fork (it is clumsy, it contains local paths) but it runs, we just wanted to give a final update for today, will continue tomorrow.

**Comment by psibre** [comment]
Thanks for the update! It can be tricky to work with resources when sphinx seems to require paths as strings... We'll see how we can solve it!

**Comment by plison** [comment]
Hi all,
To answer @naszka , OpenDial follows the following steps for the speech recognition:
1) The module AudioModule takes care of all low-level audio processing functions. It is this module that actually captures speech data from the microphones. When a particular speech segment has been recorded, its data is added to a particular state variable (denotes `s_u`) that contains the raw speech data.
2) Following the update of this state variable `s_u`, OpenDial triggers the associated models and modules via the method `trigger(state,updatedVars)`. In this case, the only module that will react to this new speech data will of course be the SphinxASR module. 
3) The SphinxASR module then access the speech data recorded in the `s_u` variable and start a RecognitionProcess (it's in a separate thread to avoid "blocking" the rest of the system while recognition is being performed). 
4) Once the recognition is completed, the process adds the recognition results to the dialogue state via the method `addUserInput(results)`. This update will then trigger new updates (from e.g. NLU, action selection, etc).

The condition `state.hasChanceNode(speechVar)` on line 166 is just defensive programming: since I'm accessing the content of the variable `speechVar` on the next line, I need to make sure the variable is present in the current dialogue state (it usually is since it has just been updated, but an additional check doesn't hurt).

**Comment by bryandeng** [comment]
I'm working on this issue along with @naszka.

Since we are using at least two dictionaries, I think it's not a good idea to hard-code paths to such dictionaries in `SphinxASR.java`.
I opened an issue in the OpenDial project: https://github.com/plison/opendial/issues/11.

BTW, should we include acoustic model files in our repository? It's usually not a good idea to include large files.
