### ISSUE TITLE
InproTK prototype

### ISSUE THREAD

**Issue by psibre** [EllaVator/EllaVator#4]

**Comment by tastyminerals** [comment]
I'll take it

**Comment by bryandeng** [comment]
I'm also on this.

**Comment by bryandeng** [comment]
I'm also on it.

**Comment by psibre** [comment]
Workflow like in https://github.com/EllaVator/EllaVator/issues/3#issuecomment-101682443 

* [ ] Text first, using the InproTK framework.
* [ ] Add TTS output (MaryTTS).
* [ ] Try to integrate speech recognition (Sphinx4).

**Comment by psibre** [comment]
Please use the [`inprotk`](/EllaVator/EllaVator/tree/inprotk) branch.

**Comment by naszka** [comment]
Interested in meeting tomorrow? I am struggling with setting up gradle, so we could play around with gradle too, then start on the inprotk demo

**Comment by tastyminerals** [comment]
Kata, I would gladly meet , unfortunately I shall be in Frankfurt tomorrow whole day. Maybe some other time this week. I have not started anything yet, so you are free to improvise ;)

**Comment by LauraRF** [comment]
Hi guys, 
I would also like to join this group. I will be in class tomorrow and hope that I've managed to set up gradle until then.

**Comment by asayeed** [comment]
The InproTK wiki, which people were asking about:
http://sourceforge.net/p/inprotk/wiki/Home/

**Comment by InfiniteConvergence** [comment]
Hi, 
  I assign myself to this.
-Stalin.

**Comment by naszka** [comment]
guys, I need help, I spent the last couple of hours trying to install inprotk, without any success. It recommends eclipse as a build environment, but it depends on opendial which is in Java8, and eclipse does not support java8, so I cannot make it an eclipse project to add to the build path of inprotk, 
How do i build it without eclipse?

**Comment by psibre** [comment]
Have a look at the [gradle branch](https://bitbucket.org/psibre/inprotk/branch/gradle) in my fork of [InproTK](https://bitbucket.org/inpro/inprotk). You can build a jar with `./gradlew jar`, but I haven't looked beyond that. It should give you an idea of how it can be built using Gradle.

**Comment by LauraRF** [comment]
Hi guys, 
I wanted to update you on how far I've gotten until now. I closely followed the instructions and used the files provided by the InproTK sourceforge wiki. I managed to download inproTK, install it, download MaryTTS, install it and build the whole thing with ant. However, I did not use gradle because it wouldn't work and I didn't use Sphinx4, because it is already integrated in InproTK. I tried the examples (demo.inpro.synthesis -> simple Pattern Demonstrator ("Zur Kreuzigung nach rechts") and the Kontonummer example) and I have to say it doesn't workt that well. I then played around with the digits.gram, digits.lex and digits.lm a bit to enter some Elevator-related stuff, but I'm not convinced by the whole thing.

**Comment by naszka** [comment]
Laura, when you used inpro, did you install opendial beforehand?
I could build it without (it only depends on marytts) but if you actually want to build a new dialog project system  it also needs opendial.

**Comment by LauraRF** [comment]
No, I didn't install opendial, not beforehand and not afterwards. But also, I didn't really build a new dialogue system, just played around with the files already available.

**Comment by psibre** [comment]
Closing for now.
