### ISSUE TITLE
Collect prompts / model dialog flow

### ISSUE THREAD

**Issue by psibre** [EllaVator/EllaVator#6]
in German and English

**Comment by Pat-Carroll** [comment]
I assign myself to modeling dialog flow.

**Comment by HoffmannAJ** [comment]
I'd also like to assign myself to modeling the dialog flow.

**Comment by tastyminerals** [comment]
I'd like to do the dialog modeling flow as well

**Comment by LauraRF** [comment]
I'll also join this group.

**Comment by HoffmannAJ** [comment]
This is my basic idea how a dialogue might look like:

![dia](https://cloud.githubusercontent.com/assets/12255262/7846873/8d371cb4-04c0-11e5-8be8-bb54798c9b88.jpeg)

U: Greeting: Keyword_for_starting_Ella
S: Greet + Offer: Hello, [What can I do for you | How can I help you]
U: Request: Take me to [[floor | room] X | Personname]
S: Grounding: You'd like to be taken to [[floor | room] X | Personname]?
U: Confirm: Yes | Do so ...
U: Reject: No | Don't ...
S: Execute: Okay I shall now take you to [[floor | room] X | Personname] //start moving//

Maybe some small talk can be added after the Request is fulfilled or while it is being fulfilled. 


Of course there could be added more variety to the sentences, but what do you think of the structure?
Could we take that do develop our variety and keywords from that?
Do you notice something I missed? Or would someone maybe like to propose a different structure?

**Comment by LauraRF** [comment]
I think that greeting from the user and from the elevator should be optional and that a user should be able to enter and directly use a request like "third floor". So I think you could enter an arrow directly from outside to the "request" circle in your diagram / structure. I think this is important if people who are in a hurry also want to use the elevator without pressing the buttons themselves. It would also be cool if in that "in-a-hurry-mode" the grounding is significantly shorter as well, such as just "third floor?" and "execute" could just be "Okay"

**Comment by LauraRF** [comment]
I made some time measurements today which might be useful in estimating how much time is spent in the elevator: 
- walking: from the door to the building to the aquarium took me 54 seconds
- calling the elevator in the ground floor and going up to the third: 44 seconds, it took around 4 seconds until the elevator was there and so the maximum time spent in the elevator with pressing the buttons is around 40 seconds going up, and only around 21 seconds going down, if I'm not mistaken.

I think this might help us in estimating how much time a user spends in the elevator at the moment and maybe also how long the dialogue should take. If it's not useful, then I at least had some fun running up and down the stairs ;)

**Comment by HoffmannAJ** [comment]
nice study! XD
And also: Good point.

On the other hand: I inserted the greeting from the user as the keyword to start the elevator, as it was done in the old version of the elevator.
It would be perfect if we could omit that and also skip the request part.

I had planned to do some more reading but didn't yet get around to do so. I wanted to know whether it is possible to interrupt the system while speaking. That would solve quite a few problems especially that with a user in hurry (and probably most users are in hurry if they are using an elevator)
Has someone already read about if and how you can create a system that can be interrupted any time?
If we could do that the dialogue would be way more natural! 
And especially the grounding and clarify could be done a lot quicker. 
It would enable us to do the grounding only implicit. (System:"Okay taking you to foor one" User: "No I meant two!" System: "Okay taking you to floor two")

Of course this nice feature could also lead to disadvantages: 
If the System is listening while speaking and reacting to very small request like "one" instead of "floor one" there might be some issues with the recognition. Any noise or cough could be mistaken and the system might stop talking and ask something like "oh I might have misheard where would you like to be taken instead?" even if it had understoop perfectly well.
In my opinion it would be definitely be worth a try. If we do good work on the speech recognition this feature would be just great. :)

To create a hurry-mode should actually be not a big deal, I think. It would to double all our nlu and nlg rules in worst case but given that our system won't have an incredibly large domain-file I don't see any problems with that.

**Comment by LauraRF** [comment]
So to make this more complete I'm including some examples for possible utterances based on the structure proposed by Anne-Julia. This is by no means an exhaustive list. 
Greetings user
German: 
- Hi | Hallo [Aufzug | Ella]
- Guten Morgen | Tag | Abend [Aufzug | Ella]
English: 
- Hi | Hello [Aufzug | Ella]
- Good morning | afternoon | evening [Aufzug | Ella]

Greetings Ella
German:
- Hallo. Wie kann ich Ihnen | Dir helfen?
- Hallo. Wo kann ich Dich | Sie hinbringen?
English: 
- Hello. How can I help you?
- Hello. Where can I take you to?

Grounding
German:
- Meinten Sie | Du....?
- Sagten Sie | sagtest Du...?
- Zweites Stockwerk? (hurry mode)
- Ich bringe Sie | Dich zu
English:
- Did you say...?
- You said...?
- You want to go to...?
- I'll take you to ...

Reject:
German: Nein | Ne | Quatsch | Falsch | stimmt nicht | falsch verstanden
English: No | that's wrong | no, not true | you got it wrong | you unterstood me wrong

Confirm:
German: Ja | Genau | Richtig | Exakt
English: Yes | that's right | Correct | exactly

**Comment by LauraRF** [comment]
Request
German: 
- In den ersten | zweiten | dritten [Stock] [bitte]
- Ins erste | zweite | dritte Stockwerk | Geschoss [bitte]
- In die erste | zweite | dritte Etage [bitte] || Zwischengeschoss
- Zum Raum ... [bitte]
- Zum Aquarium [bitte]
- Bringe mich zum Raum | [Eye-tracking] Versuch | Labor | Klo | Toilette
- Ich suche den Raum | das Büro von
- [Ella | Aufzug], kannst du mich in den ... Stock bringen?
- Ich möchte zu...
- Weißt du wo... ist?
- Bringe mich nach unten | oben | ins oberste | unterste Stockwerk | ganz nach oben | ganz nach unten
- Zum Ausgang | Eingang [bitte]
- Ins Erdgeschoss
- Ich möchte das Gebäude verlassen | raus

English: 
- to the first | second | third [floor | storey] [please]
- to room ... [please]
- to the aquarium
- take me to room... | to the [eye-tracking] experiment | lab | restrooms | toilet | restroom | bathroom
- I'm looking for room ... | the lab |...
- Can you take me to ...?
- I'd like to go to ...
- Do you know where .. .is?
- Tell me where... is?
- Take me to...
- to the top floor | lobby | street level | ground level | mezzanine | ground floor | up down

**Comment by tastyminerals** [comment]
A few additional time measurements.
Time for when one enters the elevator, presses a button and leaves the cabin: 
0 -> 3 floor: 25 sec.
3 -> 2 floor: 20 sec.
Doors:
Opening: 4.0 sec.
Closing: 5.5 sec.

**Comment by psibre** [comment]
@LauraRF could you convert this to a JSGF file and commit it into `src/main/resources` or somthing? :+1:

**Comment by LauraRF** [comment]
I'm working on a JSGF file and will have it uploaded on time before class.

**Comment by psibre** [comment]
Thanks!

**Comment by psibre** [comment]
(I should have said: closed in b44dcae3c1f093d512f2428f671ddcbb97846423)
